services:
  postgres:
    image: postgres:15-alpine
    container_name: rento-postgres-dev
    environment:
      POSTGRES_DB: rento_dev
      POSTGRES_USER: rento_dev
      POSTGRES_PASSWORD: dev_password
      POSTGRES_HOST_AUTH_METHOD: trust  # For local dev only
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./001_initial_schema.sql:/docker-entrypoint-initdb.d/001_schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rento_dev -d rento_dev"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - rento-network

  redis:
    image: redis:7-alpine
    container_name: rento-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - rento-network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  rento-network:
    driver: bridge